# Generated by Django 4.0 on 2024-02-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_meeting', models.DateField(blank=True, null=True)),
                ('time_of_meeting', models.CharField(blank=True, max_length=200, null=True)),
                ('place_of_meeting', models.CharField(blank=True, max_length=200, null=True)),
                ('agenda', models.FileField(blank=True, null=True, upload_to='files/')),
                ('financials', models.FileField(blank=True, null=True, upload_to='files/')),
                ('other', models.FileField(blank=True, null=True, upload_to='files/')),
            ],
        ),
    ]
