# Generated by Django 4.0 on 2024-02-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyManagementApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wing_flat', models.CharField(max_length=200)),
                ('parking_lot', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle_brand', models.CharField(blank=True, max_length=200, null=True)),
                ('rc_copy', models.CharField(blank=True, max_length=200, null=True)),
                ('sticker_number', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
