# Generated by Django 4.0 on 2024-02-06 10:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyManagementApi', '0002_membervehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
