# Generated by Django 4.0 on 2024-02-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyManagementApi', '0006_rename_se_help_aadhar_doc_househelp_house_help_aadhar_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='househelp',
            name='house_help_aadhar_doc',
            field=models.FileField(default='', upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='house_help_aadhar_number',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='house_help_address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='house_help_city',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='house_help_contact',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='house_help_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='house_help_pan_doc',
            field=models.FileField(default='', upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='house_help_pan_number',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='house_help_pin',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='house_help_state',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='other_doc',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='other_document_specifications',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
