# Generated by Django 4.0 on 2024-02-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyManagementApi', '0008_alter_househelp_house_help_aadhar_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='househelp',
            name='house_help_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='house_help_pan_number',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='house_help_state',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='other_document_specifications',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
