# Generated by Django 3.2.12 on 2024-02-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyManagementApi', '0010_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='househelp',
            name='house_help_name',
            field=models.CharField(error_messages={'blank': 'Name is required!'}, max_length=300),
        ),
    ]
