# Generated by Django 3.2.12 on 2024-02-09 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0039_alter_flatsharesdetails_application_number'),
        ('SocietyManagementApi', '0011_alter_househelp_house_help_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseHelpAllocationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_help_period_from', models.DateField(blank=True, null=True)),
                ('house_help_period_to', models.DateField(blank=True, null=True)),
                ('house_help_aadhar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aadhar_allocations_new', to='SocietyManagementApi.househelp')),
                ('house_help_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_help_name_allocations_new', to='SocietyManagementApi.househelp')),
                ('house_help_pan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pan_allocations_new', to='SocietyManagementApi.househelp')),
                ('house_help_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_help_role_allocations_new', to='SocietyManagementApi.househelp')),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_allocations_new', to='SocietyManagementApi.househelp')),
                ('wing_flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society.societyunitflatcreation')),
            ],
        ),
    ]
