# Generated by Django 3.2.12 on 2024-02-09 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyManagementApi', '0016_alter_househelpallocationmaster_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='househelpallocationmaster',
            name='aadhar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aadhar_allocations_new', to='SocietyManagementApi.househelp'),
        ),
        migrations.AlterField(
            model_name='househelpallocationmaster',
            name='pan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pan_allocations_new', to='SocietyManagementApi.househelp'),
        ),
    ]
