# Generated by Django 3.2.12 on 2024-02-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyManagementApi', '0017_auto_20240209_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='househelpallocationmaster',
            name='role',
            field=models.CharField(default='', max_length=300),
        ),
    ]
