# Generated by Django 3.2.12 on 2024-02-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyManagementApi', '0018_alter_househelpallocationmaster_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='househelpallocationmaster',
            name='role',
            field=models.CharField(max_length=300),
        ),
    ]
