# Generated by Django 3.2.12 on 2024-02-09 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0039_alter_flatsharesdetails_application_number'),
        ('SocietyManagementApi', '0019_alter_househelpallocationmaster_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='househelpallocationmaster',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='name_allocations_new', to='Society.membermastercreation'),
        ),
    ]
