# Generated by Django 3.2.12 on 2024-02-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyManagementApi', '0022_alter_househelpallocationmaster_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membervehicle',
            name='wing_flat',
        ),
        migrations.AddField(
            model_name='membervehicle',
            name='chargable',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
