# Generated by Django 3.2.12 on 2024-02-10 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0039_alter_flatsharesdetails_application_number'),
        ('SocietyManagementApi', '0024_auto_20240210_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membervehicle',
            name='parking_lot',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='membervehicle',
            name='rc_copy',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='membervehicle',
            name='sticker_number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='membervehicle',
            name='vehicle_brand',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='membervehicle',
            name='vehicle_number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='membervehicle',
            name='vehicle_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='membervehicle',
            name='wing_flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society.societyunitflatcreation'),
        ),
    ]
