# Generated by Django 3.2.12 on 2024-02-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyManagementApi', '0029_societycreationnew_societyregistrationdocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societycreationnew',
            name='admin_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='societycreationnew',
            name='admin_mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='societycreationnew',
            name='gst_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='societycreationnew',
            name='gst_number_doc',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='societycreationnew',
            name='interest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='societycreationnew',
            name='pan_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='societycreationnew',
            name='pan_number_doc',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='societycreationnew',
            name='pin_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='societycreationnew',
            name='registration_doc',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='societycreationnew',
            name='registration_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='societycreationnew',
            name='society_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='societycreationnew',
            name='society_reg_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='societycreationnew',
            name='socity_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
