# Generated by Django 3.2.12 on 2024-02-10 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyManagementApi', '0030_auto_20240210_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyBankCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(max_length=100)),
                ('beneficiary_code', models.CharField(max_length=100)),
                ('beneficiary_acc_number', models.CharField(max_length=100)),
                ('beneficiary_bank', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('society_creation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyManagementApi.societycreationnew')),
            ],
        ),
    ]
