# Generated by Django 3.2.12 on 2024-02-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyManagementApi', '0031_societybankcreation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocietyBankCreation',
            new_name='SocietyBankCreationNew',
        ),
    ]
