# Generated by Django 3.2.12 on 2024-02-10 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0039_alter_flatsharesdetails_application_number'),
        ('SocietyManagementApi', '0032_rename_societybankcreation_societybankcreationnew'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatWing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wing', models.CharField(max_length=100)),
                ('flat', models.CharField(max_length=300)),
                ('wing_flat_unique', models.CharField(max_length=100)),
                ('society_creation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society.societycreation')),
            ],
        ),
    ]
