# Generated by Django 3.2.12 on 2024-02-10 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyManagementApi', '0033_flatwing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatwing',
            name='society_creation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyManagementApi.societycreationnew'),
        ),
    ]
