# Generated by Django 3.2.12 on 2024-02-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyManagementApi', '0034_alter_flatwing_society_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatwing',
            name='wing_flat_unique',
        ),
    ]
