# Generated by Django 3.2.12 on 2024-02-11 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0039_alter_flatsharesdetails_application_number'),
        ('SocietyManagementApi', '0035_remove_flatwing_wing_flat_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyDocumentCreationNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_document', models.FileField(blank=True, null=True, upload_to='files/')),
                ('other_document_specification', models.CharField(blank=True, max_length=100, null=True)),
                ('society_creation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society.societycreation')),
            ],
        ),
    ]
