# Generated by Django 3.2.12 on 2024-02-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyManagementApi', '0036_societydocumentcreationnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societydocumentcreationnew',
            name='other_document',
            field=models.FileField(default='', upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='societydocumentcreationnew',
            name='other_document_specification',
            field=models.CharField(default='', max_length=100),
        ),
    ]
