# Generated by Django 3.2.12 on 2024-02-11 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyManagementApi', '0038_auto_20240211_0424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='societyregistrationdocuments',
            old_name='society_name',
            new_name='society_creation',
        ),
    ]
