# Generated by Django 3.2.12 on 2024-02-12 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyManagementApi', '0040_membermastercreationnew_membernomineecreationnew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membernomineecreationnew',
            name='member_name',
        ),
        migrations.DeleteModel(
            name='MemberMasterCreationNew',
        ),
        migrations.DeleteModel(
            name='MemberNomineeCreationNew',
        ),
    ]
