# Generated by Django 3.2.12 on 2024-02-12 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0042_alter_membernomineecreation_nominee_name'),
        ('SocietyManagementApi', '0041_auto_20240212_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=200)),
                ('ownership_percent', models.IntegerField(blank=True, null=True, verbose_name='Ownership %')),
                ('member_position', models.CharField(blank=True, max_length=200, null=True, verbose_name='Position')),
                ('member_dob', models.DateField(blank=True, null=True, verbose_name='DOB')),
                ('member_pan_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='PAN No.')),
                ('member_aadhar_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='Aadhar No.')),
                ('member_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('member_state', models.CharField(blank=True, max_length=200, null=True, verbose_name='State')),
                ('member_pin_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pin Code')),
                ('member_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('member_contact', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contact No.')),
                ('member_emergency_contact', models.CharField(blank=True, max_length=200, null=True, verbose_name='Emerg. Contact No.')),
                ('member_occupation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Occupation')),
                ('member_is_primary', models.BooleanField(blank=True, default=False, null=True, verbose_name='Primary')),
                ('date_of_admission', models.DateField(blank=True, null=True)),
                ('age_at_date_of_admission', models.IntegerField(blank=True, null=True)),
                ('sales_agreement', models.FileField(blank=True, null=True, upload_to='files/')),
                ('other_attachment', models.FileField(blank=True, null=True, upload_to='files/')),
                ('date_of_entrance_fees', models.DateField(blank=True, null=True)),
                ('date_of_cessation', models.DateField(blank=True, null=True)),
                ('reason_for_cessation', models.CharField(blank=True, max_length=200, null=True)),
                ('flat_status', models.CharField(blank=True, max_length=200, null=True)),
                ('same_flat_member_identification', models.CharField(blank=True, max_length=100, null=True)),
                ('wing_flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society.societyunitflatcreation', verbose_name='Flat No.')),
            ],
        ),
        migrations.CreateModel(
            name='Nominees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominee_name', models.CharField(max_length=300)),
                ('date_of_nomination', models.DateField(blank=True, null=True)),
                ('relation_with_nominee', models.CharField(blank=True, max_length=300, null=True)),
                ('nominee_sharein_percent', models.IntegerField(blank=True, null=True)),
                ('nominee_dob', models.DateField(blank=True, null=True)),
                ('nominee_aadhar_no', models.CharField(blank=True, max_length=300, null=True)),
                ('nominee_pan_no', models.CharField(blank=True, max_length=300, null=True)),
                ('nominee_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nominee_address', models.CharField(blank=True, max_length=300, null=True)),
                ('nominee_state', models.CharField(blank=True, max_length=300, null=True)),
                ('nominee_pin_code', models.CharField(blank=True, max_length=300, null=True)),
                ('nominee_contact', models.CharField(blank=True, max_length=300, null=True)),
                ('nominee_emergency_contact', models.CharField(blank=True, max_length=300, null=True)),
                ('member_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyManagementApi.members')),
            ],
        ),
    ]
