# Generated by Django 4.0 on 2024-02-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyManagementApi', '0043_alter_nominees_relation_with_nominee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominees',
            name='relation_with_nominee',
            field=models.CharField(max_length=300),
        ),
    ]
