# Generated by Django 4.0 on 2024-02-17 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyManagementApi', '0045_alter_nominees_relation_with_nominee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societydocumentcreationnew',
            name='society_creation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyManagementApi.societycreationnew'),
        ),
    ]
