# Generated by Django 4.0 on 2024-02-17 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0047_alter_membernomineecreation_member_name'),
        ('SocietyManagementApi', '0048_sharesdetailsmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharesdetailsmaster',
            name='unique_member_shares',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Society.membermastercreation'),
        ),
    ]
