# Generated by Django 4.0 on 2024-02-17 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0047_alter_membernomineecreation_member_name'),
        ('SocietyManagementApi', '0050_homeloandetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_number', models.CharField(max_length=300)),
                ('gst_state', models.CharField(blank=True, max_length=300, null=True)),
                ('gst_billing_name', models.CharField(blank=True, max_length=300, null=True)),
                ('gst_billing_address', models.CharField(blank=True, max_length=300, null=True)),
                ('gst_contact_no', models.CharField(blank=True, max_length=300, null=True)),
                ('unique_member_shares', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Society.membermastercreation')),
                ('wing_flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society.societyunitflatcreation')),
            ],
        ),
    ]
