# Generated by Django 4.0 on 2024-02-17 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0047_alter_membernomineecreation_member_name'),
        ('SocietyManagementApi', '0052_membervehicleregister_delete_membervehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membervehicleregister',
            name='unique_member_shares',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society.membermastercreation'),
        ),
    ]
