# Generated by Django 4.0 on 2024-02-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyManagementApi', '0053_alter_membervehicleregister_unique_member_shares'),
    ]

    operations = [
        migrations.RenameField(
            model_name='househelpallocationmaster',
            old_name='aadhar',
            new_name='aadhar_pan',
        ),
        migrations.RemoveField(
            model_name='househelpallocationmaster',
            name='pan',
        ),
    ]
