# Generated by Django 4.0 on 2024-02-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyManagementApi', '0054_rename_aadhar_househelpallocationmaster_aadhar_pan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='househelpallocationmaster',
            old_name='name',
            new_name='house_help_name',
        ),
    ]
