# Generated by Django 4.0 on 2024-02-17 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyManagementApi', '0055_rename_name_househelpallocationmaster_house_help_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='househelpallocationmaster',
            name='aadhar_pan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aadhar_pan_allocations_new', to='SocietyManagementApi.househelp'),
        ),
    ]
