# Generated by Django 4.0 on 2024-02-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyManagementApi', '0056_alter_househelpallocationmaster_aadhar_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societybankcreationnew',
            name='is_primary',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
