# Generated by Django 4.0 on 2024-01-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='societybankcreation',
            name='is_primary',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
