# Generated by Django 4.0 on 2024-01-21 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0003_societyunitflatcreation_unit_flat_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberMasterCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(blank=True, max_length=200, null=True)),
                ('ownership_percent', models.IntegerField()),
                ('member_position', models.CharField(blank=True, max_length=200, null=True)),
                ('member_dob', models.DateField(blank=True, null=True)),
                ('member_pan_no', models.CharField(blank=True, max_length=200, null=True)),
                ('member_aadhar_no', models.CharField(blank=True, max_length=200, null=True)),
                ('member_address', models.CharField(blank=True, max_length=200, null=True)),
                ('member_state', models.CharField(blank=True, max_length=200, null=True)),
                ('member_pin_code', models.CharField(blank=True, max_length=200, null=True)),
                ('member_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('member_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('member_emergency_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('member_occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('member_is_primary', models.BooleanField(blank=True, default=False, null=True)),
                ('wing_flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society.societyunitflatcreation')),
            ],
        ),
        migrations.CreateModel(
            name='MemberNomineeCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominee_name', models.CharField(blank=True, max_length=300, null=True)),
                ('date_of_nomination', models.DateField(blank=True, null=True)),
                ('relation_with_nominee', models.CharField(blank=True, max_length=300, null=True)),
                ('nominee_sharein_percent', models.IntegerField(blank=True, null=True)),
                ('nominee_dob', models.DateField(blank=True, null=True)),
                ('nominee_aadhar_no', models.CharField(blank=True, max_length=300, null=True)),
                ('nominee_pan_no', models.CharField(blank=True, max_length=300, null=True)),
                ('nominee_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nominee_address', models.CharField(blank=True, max_length=300, null=True)),
                ('nominee_state', models.CharField(blank=True, max_length=300, null=True)),
                ('nominee_pin_code', models.CharField(blank=True, max_length=300, null=True)),
                ('nominee_contact', models.CharField(blank=True, max_length=300, null=True)),
                ('nominee_emergency_contact', models.CharField(blank=True, max_length=300, null=True)),
                ('member_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society.membermastercreation')),
            ],
        ),
    ]
