# Generated by Django 4.0 on 2024-01-21 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0004_membermastercreation_membernomineecreation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membernomineecreation',
            name='member_name',
        ),
        migrations.AddField(
            model_name='membernomineecreation',
            name='wing_flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Society.societyunitflatcreation'),
        ),
    ]
