# Generated by Django 4.0 on 2024-01-21 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0005_remove_membernomineecreation_member_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membernomineecreation',
            name='wing_flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society.societyunitflatcreation'),
        ),
    ]
