# Generated by Django 4.0 on 2024-01-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0006_alter_membernomineecreation_wing_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermastercreation',
            name='ownership_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
