# Generated by Django 4.0 on 2024-01-22 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0007_alter_membermastercreation_ownership_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatSharesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_folio_number', models.CharField(blank=True, max_length=300, null=True)),
                ('id_shares_date', models.DateField(blank=True, null=True)),
                ('id_application_number', models.CharField(blank=True, max_length=300, null=True)),
                ('id_shares_certificate', models.CharField(blank=True, max_length=300, null=True)),
                ('id_allotment_number', models.CharField(blank=True, max_length=300, null=True)),
                ('id_shares_from', models.CharField(blank=True, max_length=300, null=True)),
                ('id_shares_to', models.CharField(blank=True, max_length=300, null=True)),
                ('id_shares_transfer_date', models.DateField(blank=True, null=True)),
                ('id_total_amount_received', models.IntegerField(blank=True, null=True)),
                ('id_total_amount_date', models.DateField(blank=True, null=True)),
                ('id_transfer_from_folio_no', models.CharField(blank=True, max_length=300, null=True)),
                ('id_transfer_to_folio_no', models.CharField(blank=True, max_length=300, null=True)),
                ('wing_flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society.societyunitflatcreation')),
            ],
        ),
    ]
