# Generated by Django 4.0 on 2024-01-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0008_flatsharesdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatsharesdetails',
            old_name='id_allotment_number',
            new_name='allotment_number',
        ),
        migrations.RenameField(
            model_name='flatsharesdetails',
            old_name='id_application_number',
            new_name='application_number',
        ),
        migrations.RenameField(
            model_name='flatsharesdetails',
            old_name='id_folio_number',
            new_name='folio_number',
        ),
        migrations.RenameField(
            model_name='flatsharesdetails',
            old_name='id_shares_certificate',
            new_name='shares_certificate',
        ),
        migrations.RenameField(
            model_name='flatsharesdetails',
            old_name='id_shares_date',
            new_name='shares_date',
        ),
        migrations.RenameField(
            model_name='flatsharesdetails',
            old_name='id_shares_from',
            new_name='shares_from',
        ),
        migrations.RenameField(
            model_name='flatsharesdetails',
            old_name='id_shares_to',
            new_name='shares_to',
        ),
        migrations.RenameField(
            model_name='flatsharesdetails',
            old_name='id_shares_transfer_date',
            new_name='shares_transfer_date',
        ),
        migrations.RenameField(
            model_name='flatsharesdetails',
            old_name='id_total_amount_date',
            new_name='total_amount_date',
        ),
        migrations.RenameField(
            model_name='flatsharesdetails',
            old_name='id_total_amount_received',
            new_name='total_amount_received',
        ),
        migrations.RenameField(
            model_name='flatsharesdetails',
            old_name='id_transfer_from_folio_no',
            new_name='transfer_from_folio_no',
        ),
        migrations.RenameField(
            model_name='flatsharesdetails',
            old_name='id_transfer_to_folio_no',
            new_name='transfer_to_folio_no',
        ),
    ]
