# Generated by Django 4.0 on 2024-01-22 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0009_rename_id_allotment_number_flatsharesdetails_allotment_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatHomeLoanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_loan_name', models.CharField(blank=True, max_length=300, null=True)),
                ('bank_loan_object', models.CharField(blank=True, max_length=300, null=True)),
                ('bank_loan_date', models.DateField(blank=True, null=True)),
                ('bank_loan_value', models.CharField(blank=True, max_length=300, null=True)),
                ('bank_loan_acc_no', models.CharField(blank=True, max_length=300, null=True)),
                ('bank_loan_installment', models.CharField(blank=True, max_length=300, null=True)),
                ('bank_loan_status', models.BooleanField(blank=True, default=False, null=True)),
                ('bank_loan_remark', models.CharField(blank=True, max_length=300, null=True)),
                ('bank_noc_file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('wing_flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society.societyunitflatcreation')),
            ],
        ),
    ]
