# Generated by Django 4.0 on 2024-01-24 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0014_alter_membermastercreation_member_aadhar_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermastercreation',
            name='wing_flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society.societyunitflatcreation', verbose_name='name'),
        ),
    ]
