# Generated by Django 4.0 on 2024-01-24 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0015_alter_membermastercreation_wing_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermastercreation',
            name='wing_flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society.societyunitflatcreation'),
        ),
    ]
