# Generated by Django 4.0 on 2024-01-24 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0017_alter_membermastercreation_wing_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermastercreation',
            name='member_aadhar_no',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Aadhar No.'),
        ),
        migrations.AlterField(
            model_name='membermastercreation',
            name='member_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='membermastercreation',
            name='member_contact',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Contact No.'),
        ),
        migrations.AlterField(
            model_name='membermastercreation',
            name='member_dob',
            field=models.DateField(blank=True, null=True, verbose_name='DOB'),
        ),
        migrations.AlterField(
            model_name='membermastercreation',
            name='member_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='membermastercreation',
            name='member_emergency_contact',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Emerg. Contact No.'),
        ),
        migrations.AlterField(
            model_name='membermastercreation',
            name='member_is_primary',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Primary'),
        ),
        migrations.AlterField(
            model_name='membermastercreation',
            name='member_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='membermastercreation',
            name='member_occupation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='membermastercreation',
            name='member_pan_no',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='PAN No.'),
        ),
        migrations.AlterField(
            model_name='membermastercreation',
            name='member_pin_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pin Code'),
        ),
        migrations.AlterField(
            model_name='membermastercreation',
            name='member_position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='membermastercreation',
            name='member_state',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='membermastercreation',
            name='ownership_percent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ownership %'),
        ),
        migrations.AlterField(
            model_name='membermastercreation',
            name='wing_flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society.societyunitflatcreation', verbose_name='Flat No.'),
        ),
    ]
