# Generated by Django 4.0 on 2024-01-27 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0019_remove_membernomineecreation_wing_flat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membernomineecreation',
            name='member_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society.membermastercreation'),
        ),
    ]
