# Generated by Django 4.0 on 2024-01-29 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0020_alter_membernomineecreation_member_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenentMasterCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenent_name', models.CharField(blank=True, max_length=300, null=True)),
                ('tenent_pan_number', models.CharField(blank=True, max_length=300, null=True)),
                ('tenent_pan_doc', models.FileField(blank=True, null=True, upload_to='files/')),
                ('tenent_contact', models.CharField(blank=True, max_length=300, null=True)),
                ('tenent_aadhar_number', models.CharField(blank=True, max_length=300, null=True)),
                ('tenent_aadhar_doc', models.FileField(blank=True, null=True, upload_to='files/')),
                ('tenent_address', models.CharField(blank=True, max_length=300, null=True)),
                ('tenent_city', models.CharField(blank=True, max_length=300, null=True)),
                ('tenent_state', models.CharField(blank=True, max_length=300, null=True)),
                ('tenent_pin_code', models.CharField(blank=True, max_length=300, null=True)),
                ('tenent_email', models.CharField(blank=True, max_length=300, null=True)),
                ('tenent_other_doc', models.FileField(blank=True, null=True, upload_to='files/')),
                ('tenent_doc_specification', models.CharField(blank=True, max_length=300, null=True)),
                ('wing_flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society.societyunitflatcreation')),
            ],
        ),
        migrations.CreateModel(
            name='TenantAllocationCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, max_length=300, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=300, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=300, null=True)),
                ('tenant_from_date', models.CharField(blank=True, max_length=300, null=True)),
                ('tenant_to_date', models.CharField(blank=True, max_length=300, null=True)),
                ('tenant_agreement', models.CharField(blank=True, max_length=300, null=True)),
                ('tenant_noc', models.CharField(blank=True, max_length=300, null=True)),
                ('tenent_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society.tenentmastercreation')),
                ('wing_flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society.societyunitflatcreation')),
            ],
        ),
    ]
