# Generated by Django 4.0 on 2024-01-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0021_tenentmastercreation_tenantallocationcreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantallocationcreation',
            name='tenant_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantallocationcreation',
            name='tenant_noc',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='tenantallocationcreation',
            name='tenant_to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
