# Generated by Django 4.0 on 2024-01-31 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0024_rename_aadhar_number_tenantallocationcreation_flat_primary_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseHelpCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_help_name', models.CharField(blank=True, max_length=300, null=True)),
                ('house_help_pan_number', models.CharField(blank=True, max_length=300, null=True)),
                ('house_help_pan_doc', models.FileField(blank=True, null=True, upload_to='files/')),
                ('house_help_contact', models.CharField(blank=True, max_length=300, null=True)),
                ('house_help_aadhar_number', models.CharField(blank=True, max_length=300, null=True)),
                ('se_help_aadhar_doc', models.FileField(blank=True, null=True, upload_to='files/')),
                ('house_help_address', models.CharField(blank=True, max_length=300, null=True)),
                ('house_help_city', models.CharField(blank=True, max_length=300, null=True)),
                ('house_help_state', models.CharField(blank=True, max_length=300, null=True)),
                ('house_help_pin', models.CharField(blank=True, max_length=300, null=True)),
                ('other_doc', models.FileField(blank=True, null=True, upload_to='files/')),
                ('document_specifications', models.FileField(blank=True, null=True, upload_to='files/')),
                ('wing_flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society.societyunitflatcreation')),
            ],
        ),
    ]
