# Generated by Django 4.0 on 2024-01-31 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0025_househelpcreation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseHelpAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=300, null=True)),
                ('aadhar', models.CharField(blank=True, max_length=300, null=True)),
                ('pan', models.CharField(blank=True, max_length=300, null=True)),
                ('house_help_name', models.CharField(blank=True, max_length=300, null=True)),
                ('house_help_role', models.CharField(blank=True, max_length=300, null=True)),
                ('house_help_period_from', models.DateField(blank=True, null=True)),
                ('house_help_period_to', models.DateField(blank=True, null=True)),
                ('wing_flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society.societyunitflatcreation')),
            ],
        ),
    ]
