# Generated by Django 4.0 on 2024-01-31 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0026_househelpallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='househelpallocation',
            name='aadhar',
        ),
        migrations.RemoveField(
            model_name='househelpallocation',
            name='pan',
        ),
        migrations.AddField(
            model_name='househelpallocation',
            name='house_help_aadhar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aadhar_allocations', to='Society.househelpcreation'),
        ),
        migrations.AddField(
            model_name='househelpallocation',
            name='house_help_pan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pan_allocations', to='Society.househelpcreation'),
        ),
        migrations.AlterField(
            model_name='househelpallocation',
            name='owner_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_allocations', to='Society.househelpcreation'),
        ),
    ]
