# Generated by Django 4.0 on 2024-01-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0027_remove_househelpallocation_aadhar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='househelpallocation',
            name='house_help_aadhar',
        ),
        migrations.RemoveField(
            model_name='househelpallocation',
            name='house_help_pan',
        ),
        migrations.AddField(
            model_name='househelpallocation',
            name='aadhar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='househelpallocation',
            name='pan',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='househelpallocation',
            name='owner_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
