# Generated by Django 4.0 on 2024-02-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0030_membermastercreation_date_of_admission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membermastercreation',
            name='status',
        ),
        migrations.AddField(
            model_name='membermastercreation',
            name='flat_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='membermastercreation',
            name='member_current_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
