# Generated by Django 4.0 on 2024-02-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0032_remove_membermastercreation_member_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermastercreation',
            name='same_flat_member_identification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
