# Generated by Django 4.0 on 2024-02-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0033_membermastercreation_same_flat_member_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermastercreation',
            name='date_of_cessation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
