# Generated by Django 4.0 on 2024-02-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0035_membermastercreation_age_at_date_of_admission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatsharesdetails',
            name='folio_number',
            field=models.CharField(default='', max_length=300),
        ),
    ]
