# Generated by Django 4.0 on 2024-02-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0036_alter_flatsharesdetails_folio_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatsharesdetails',
            name='folio_number',
            field=models.CharField(max_length=300),
        ),
    ]
