# Generated by Django 3.2.12 on 2024-02-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0041_alter_membernomineecreation_nominee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membernomineecreation',
            name='nominee_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
