# Generated by Django 4.0 on 2024-02-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0042_alter_membernomineecreation_nominee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flathomeloandetails',
            name='bank_loan_name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
