# Generated by Django 4.0 on 2024-02-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0044_alter_flathomeloandetails_bank_loan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatgstdetails',
            name='gst_number',
            field=models.CharField(default='', max_length=300),
        ),
    ]
