# Generated by Django 4.0 on 2024-02-15 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0046_alter_flatgstdetails_gst_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membernomineecreation',
            name='member_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='Society.membermastercreation'),
        ),
    ]
